### ISSUE TITLE
change page title

### ISSUE THREAD

**Issue by ceduliocezar** [rtfpessoa/diff2html-cli#34] opened 2018-04-03 21:10 UTC
It is not possible to change the title of the output html diff from cli?

By default it displays Diff to HTML by rtfpessoa.

I would like to pass a parameter to  change it, but wasn't able to find it in the docs.

**Comment by rtfpessoa** [comment] 2018-04-03 22:24
Duplicate of https://github.com/rtfpessoa/diff2html-cli/issues/33

**Closed as completed** 2018-04-03 22:24 UTC

**Comment by eduardocopat** [comment] 2020-12-11 00:18
I still think there would be value to have a flag to set a title (for example, `--title My Title`).

**Comment by rtfpessoa** [comment] 2021-02-20 11:43
Feel free to send a PR
